commerce/urls.py
from django.urls import path
from.import views
app_name="commerce"
urlpatterns=[
      path("accueil/",views.accueil, name='accueil'),
      path("detail/<product_id>",views.detail,name='detail'),
      path("product/<product_id>",views.display_product, name='display_product'),
      path("commande/<product_id>",views.commande,name="commande"),
       ]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('commerce/',include('commerce.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

commerce/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
class Product(models.Model):
    """presentation du produit"""
    name=models.CharField(max_length=200,verbose_name="Nom du produit")
    short_desc=models.CharField(max_length=150,verbose_name="Description courte")
    long_desc=models.TextField(verbose_name="Description longue")
    image=models.ImageField(upload_to='photo/',verbose_name="Miniature du produit",null=True)
    price=models.CharField(max_length=200,verbose_name="Prix du produit")
   
    class Meta:
        verbose_name="Produit"
        verbose_name_plural="Produits"

        def __str__ (self):
            return self.name

class Photo(models.Model):
    """les photos montrent les differents produits"""
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    product_photo=models.ImageField(upload_to='photo/')
   
class Order(models.Model):
    created_at = models.DateTimeField('date d\'envoi',default=timezone.now)
    contacted = models.BooleanField('demande traitée', default=False)
    contact = models.ForeignKey("Contact",on_delete=models.CASCADE,default=0)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,default=0)
    class Meta:
        verbose_name="Commande"
        verbose_name_plural="Commandes"

    def __str__(self):
        return self.contact.name


    
class Contact(models.Model):
    email=models.EmailField(max_length=200,verbose_name="Email",default=0)
    name=models.CharField(max_length=200,verbose_name="Nom",default=0)
    city=models.CharField(max_length=200,verbose_name="Ville",default=0)
    quarter=models.CharField(max_length=200,verbose_name="Quartier",default=0)
    street=models.CharField(max_length=200,verbose_name="Numéro de rue",default=0)
    door=models.CharField(max_length=200,verbose_name="Numéro de porte",default=0)
    phone=models.CharField(max_length=200,verbose_name="Téléphone",default=0)

    class Meta:
        verbose_name="Contact"
        verbose_name_plural="Contacts"
        
    def __str__(self):
        return self.name

        
        




                                
    
    
    
    
    

commerce/forms.py
from django import forms
from.models import *
from django.forms.utils import ErrorList


class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields="__all__"


class ParagraphErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()

    def as_divs(self):
        if not self: return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<p class="small error">%s</p>' % e for e in self])



    

commerce/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
import datetime
from django.contrib import messages
from.models import *
from.forms import *


# Create your views here.


def accueil(request):
    products = Product.objects.order_by('-id')[:100]
    carousel = Photo.objects.all().order_by('-id')[:5]

    return render(request, 'commerce/accueil.html',
                  {'products': products,'carousel': carousel})



def display_product(request, product_id):
    """
    Cette fonction permet de visualiser un produit.
    :type request:
    :param request:
    :param product_id: Id du produit à visualiser
    :return:
    """

    product = get_object_or_404(Product, pk=product_id)
    pictures = Photo.objects.filter(product__pk=product.id)

    return render(request, 'commerce/product.html', {'product': product, 'pictures': pictures})

def commande(request,product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {
        'product_name': product.name,
        'product_id': product.id,
        'image': product.image,
    }
    if request.method == 'POST':
        form = ContactForm(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']
            city = form.cleaned_data['city']
            quarter = form.cleaned_data['quarter']
            street=form.cleaned_data['street']
            door=form.cleaned_data['door']
            phone=form.cleaned_data['phone'] 

            try:
                    contact = Contact.objects.filter(email=email, name=name,
                            city=city,
                            quarter=quarter,
                            street=street,
                            door=door,
                            phone=phone)
                    if not contact.exists():
                        contact = Contact.objects.create(
                            email=email,
                            name=name,
                            city=city,
                            quarter=quarter,
                            street=street,
                            door=door,
                            phone=phone
                        )
                    else:
                        contact = contact.first()

                    product = get_object_or_404(Product, id=product_id)
                    order = Order.objects.create(
                        contact=contact,
                        product=product 
                    )
                    product.save()
                    return render(request,"commerce/merci.html",context)
            except:
                form.errors['internal'] = "Une erreur interne est apparue. Merci de recommencer votre requête."

    else:
        form = ContactForm()
    context['form'] = form
    context['errors'] = form.errors.items()
    return render(request, 'commerce/commande.html', context)




 
   

def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {
        'product_name': product.name,
        'product_id': product.id,
        'image': product.image,
    }

    if request.method == 'POST':
        form = ContactForm(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']
            city = form.cleaned_data['city']
            quarter = form.cleaned_data['quarter']
            street=form.cleaned_data['street']
            door=form.cleaned_data['door']
            phone=form.cleaned_data['phone'] 

            try:
                    contact = Contact.objects.filter(email=email)
                    if not contact.exists():
                        contact = Contact.objects.create(
                            email=email,
                            name=name,
                            city=city,
                            quarter=quarter,
                            street=street,
                            door=door,
                            phone=phone
                        )
                    else:
                        contact = contact.first()

                    product = get_object_or_404(Product, id=product_id)
                    order = Order.objects.create(
                        contact=contact,
                        product=product 
                    )
                    product.save()
                    return render(request, 'commerce/accueil.html', context)
            except:
                form.errors['internal'] = "Une erreur interne est apparue. Merci de recommencer votre requête."

    else:
        form = ContactForm()
    context['form'] = form
    context['errors'] = form.errors.items()
    return render(request, 'commerce/detail.html', context)

commerce/templates/commerce/accueil.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    <div class="row">

            <div class="col-md-3">
                <p class="lead">Rayons</p>       
            </div>

            <div class="col-md-9">
                {% if carousel %}
                <p class="lead">À la une</p>
                <div class="row carousel-holder">
                    <div class="col-md-12">
                        <div id="carousel" class="carousel slide" data-interval="5000" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for picture in carousel %}
                                    <li data-target="#carousel" data-slide-to="{{ forloop.counter0 }}" class=""></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                                {% for picture in carousel %}
                                    <div class="item{% if forloop.counter0 == 0 %} active{% endif %}">
                                        <img class="slide-image" src="/media/{{ picture.product_photo }}" />
                                        <div class="carousel-caption">
                                            <h3><a style="color:white" href="{% url 'commerce:display_product' picture.product.id %}">{{ picture.product.name }}</a></h3>
                                            <p>{{ picture.product.short_desc }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}

                <p class="lead">Derniers produits</p>
                <div class="row">

                    {% for product in products %}
                        <div class="col-sm-4 col-lg-4 col-md-4">
                            <div class="thumbnail">
                                {% if product.image %}
                                   <a href="{% url 'commerce:display_product' product.id %}"> <img src="/media/{{ product.image}}" alt=""></a>
                                {% else %}
                                    <img class="slide-image" src="/media/"http://placehold.it/320x150" alt="">
                                {% endif %}
                                <div class="caption">
                                    <h4 class="pull-right">{{ product.price }} FCFA</h4>
                                    <h4><a href="{% url 'commerce:display_product' product.id %}">{{ product.name }}</a>
                                    </h4>
                                    <p>{{ product.short_desc }}</p>
                                </div>
                                <!--
                                <div class="ratings">
                                    <p class="pull-right">18 reviews</p>
                                    <p>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                    </p>
                                </div>
                                -->
                            </div>
                        </div>
                    {% endfor %}

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <h4><a href="#">Vous en voulez plus ?</a>
                        </h4>
                        <p>N'hésitez pas à parcourir nos différents rayons par l'intermédiaire de la colonne de droite. Vous-y découvrirez de nombreuses pépites !</p>
                        <p>À vos paniers !</p>
                    </div>

                </div>

            </div>

        </div>

{% endblock %}

commerce/templates/commerce/commande.html
{% extends "base.html" %}
{% block body %}
<div class="formu">
{% if product %}Votre commande a bien été envoyé !{% endif %}

<form action="{% url "commerce:commande" product_id=product_id  %}" method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Envoyer" />

</form>
</div>
{% endblock %}

commerce/templates/commerce/detail.html
{% extends 'base.html' %}

{% block body %}
<hr>
<h1 class="intro-text text-center">{{ product.name }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ product.image }}" alt="{{ product.short_desc }}" class="img-responsive">
</div>
  <h2 class="text-center artist_name">Commander {{ product.name }}</h2>
  <p style="margin-bottom: 20px;">votre produit{{ product.name }} vous sera livré à domicile </p>
  <form class="form-inline" action="{% url 'commerce:detail' product_id=product_id %}" method="post">
    {% csrf_token %}
    <div class="form-group {% if form.name.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.name.id_for_label }}" class="control-label">Nom</label>
      {{ form.name }}
    </div>
        <div class="form-group {% if form.city.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.city.id_for_label }}" class="control-label">City</label>
      {{ form.city }}
    </div>
        <div class="form-group {% if form.quarter.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.quarter.id_for_label }}" class="control-label">Quartier</label>
      {{ form.quarter }}
    </div>
        <div class="form-group {% if form.street.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.street.id_for_label }}" class="control-label">Rue</label>
      {{ form.street }}
    </div>
        <div class="form-group {% if form.door.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.door.id_for_label }}" class="control-label">Numéro de porte</label>
      {{ form.door }}
    </div>
        <div class="form-group {% if form.phone.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.phone.id_for_label }}" class="control-label">Numéro de téléphone</label>
      {{ form.phone }}
    </div>
    <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.email.id_for_label }}" class="control-label">E-mail</label>
      {{ form.email }}
    </div>
    <input type="hidden" class="hidden" value="{{ product_id }}" name="product_id">

    <button type="submit" class="btn btn-success">Commander</button>
  </form>
  {% if errors %}
    <div>
      {% for key, error in errors %}
        {% autoescape off %}
          {{ error }}
        {% endautoescape %}
      {% endfor %}
    </div>
  {% endif %}


</div>


{% endblock %}

commerce/templates/commerce/merci.html
{% extends "base.html" %}
{% load static %}
{% block body %}

<p>Merci d'avoir choisi SkerlyVente pour vos achats,nous vous enverrons un message un peu plutard.Bonne journée!!!!</p>
<img src="{% static 'femme.jpg' %}"/>


{% endblock %}

commerce/templates/commerce/product.html
{% extends "base.html" %}

{% block body %}
    <div class="row">

            <div class="col-md-3">
                <p class="lead">Rayons</p>
            </div>

            <div class="col-md-9">
                <p class="lead">{{ product.name }}<a href="{% url 'commerce:commande' product.id %}" class="pull-right btn btn-success"><i class="fa fa-shopping-cart"></i> Commander pour <strong>{{ product.price}}</strong> FCFA</a></p>

                <p>{{ product.short_desc }}</p>

                {% if pictures %}
                    <div class="row carousel-holder">
                        <div class="col-md-12">
                            <div id="carousel" class="carousel slide" data-interval="5000" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    {% for picture in pictures %}
                                        <li data-target="#carousel" data-slide-to="{{ forloop.counter0 }}" class=""></li>
                                    {% endfor %}
                                </ol>
                                <div class="carousel-inner">
                                    {% for picture in pictures %}
                                        <div class="item{% if forloop.counter0 == 0 %} active{% endif %}">
                                            <img class="slide-image" src="/media/{{ picture.product_photo }}" />
                                        </div>
                                    {% endfor %}
                                </div>
                                <a class="left carousel-control" href="#carousel" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left"></span>
                                </a>
                                <a class="right carousel-control" href="#carousel" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endif %}

                <p>{{ product.long_desc }}</p>




            </div>

        </div>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "favicon.ico" %}">

    <title>{% block title %}SkerlyVente, vos produits à petits prix{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Font awesome core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="{% static "css/style.css" %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<nav class="navbar navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'commerce:accueil' %}"><i class="fa fa-gamepad"></i> SkerlyVente <sub class="text-muted"><small>Vos produits préférés à petits prix !</small></sub></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} {% if message.tags == 'error' %}alert-danger{% endif %} fade in">
                {% autoescape off %}{{ message }}{% endautoescape %}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}{% endblock %}

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

{% block javascripts %}{% endblock %}

</body></html>